#!/bin/bash

# It's best to remove errexit so that the loop continues even if the server crashes.
set -o pipefail
set -o nounset

# Run migrations only once.
python manage.py migrate

# Loop to restart the server if it crashes.
while true; do
    uvicorn config.asgi:application --host 0.0.0.0 --reload --reload-include '*.html'
    echo "Uvicorn server stopped unexpectedly. Sleeping for 5 seconds..."
    sleep 5
done
