# Generated by Django 5.0.12 on 2025-04-02 02:13

import autoslug.fields
import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
import eleganza.products.validators
import imagekit.models.fields
import mptt.fields
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when object was soft-deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of creation', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, help_text='Unique variant identifier', max_length=50, unique=True, verbose_name='Variant SKU')),
                ('price_modifier_currency', djmoney.models.fields.CurrencyField(choices=[('LYD', 'Libyan Dinar')], default='LYD', editable=False, max_length=3)),
                ('price_modifier', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), help_text='Price adjustment from base', max_digits=14, verbose_name='Price Modifier')),
                ('is_default', models.BooleanField(default=False, help_text='Primary display variant', verbose_name='Default Variant')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Variant visibility', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when object was soft-deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of creation', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Full product name', max_length=255, verbose_name='Product Name')),
                ('slug', models.SlugField(help_text='Unique product URL identifier', unique=True, verbose_name='URL Slug')),
                ('sku', models.CharField(db_index=True, help_text='Base stock keeping unit', max_length=50, unique=True, verbose_name='SKU')),
                ('description', models.TextField(help_text='Detailed product description', verbose_name='Description')),
                ('original_price_currency', djmoney.models.fields.CurrencyField(choices=[('LYD', 'Libyan Dinar')], default='LYD', editable=False, max_length=3)),
                ('original_price', djmoney.models.fields.MoneyField(decimal_places=2, help_text="Manufacturer's suggested price", max_digits=14, verbose_name='Original Price')),
                ('selling_price_currency', djmoney.models.fields.CurrencyField(choices=[('LYD', 'Libyan Dinar')], default='LYD', editable=False, max_length=3)),
                ('selling_price', djmoney.models.fields.MoneyField(decimal_places=2, help_text='Base price before discounts', max_digits=14, verbose_name='Selling Price')),
                ('final_price_currency', djmoney.models.fields.CurrencyField(choices=[('LYD', 'Libyan Dinar')], default='LYD', editable=False, max_length=3)),
                ('final_price', djmoney.models.fields.MoneyField(decimal_places=2, editable=False, help_text='Calculated price after discounts', max_digits=14, verbose_name='Final Price')),
                ('discount_type', models.CharField(choices=[('none', 'No Discount'), ('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], default='none', max_length=10, verbose_name='Discount Type')),
                ('discount_amount_currency', djmoney.models.fields.CurrencyField(choices=[('LYD', 'Libyan Dinar')], default='LYD', editable=False, max_length=3, null=True)),
                ('discount_amount', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Fixed amount discount', max_digits=14, null=True, verbose_name='Discount Amount')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Percentage discount', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99.99)], verbose_name='Discount Percentage')),
                ('has_variants', models.BooleanField(db_index=True, default=False, help_text='Enable product variants', verbose_name='Has Variants')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Feature in prominent areas', verbose_name='Featured')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Product visibility', verbose_name='Active')),
                ('average_rating', models.DecimalField(decimal_places=1, default=0.0, editable=False, max_digits=3, verbose_name='Average Rating')),
                ('review_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Review Count')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text="Display value (e.g., 'Red', 'XXL')", max_length=100, verbose_name='Option Value')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order in selectors (lower first)', verbose_name='Sort Order')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle option visibility', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Product Option',
                'verbose_name_plural': 'Product Options',
                'ordering': ['attribute__name', 'sort_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('variant', models.OneToOneField(help_text='Linked variant', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='inventory', serialize=False, to='products.productvariant')),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Physical inventory count', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Stock')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Restock trigger level', verbose_name='Low Stock Alert')),
                ('last_restock', models.DateTimeField(blank=True, null=True, verbose_name='Last Restock')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventory Records',
            },
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='Parent Product'),
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Customer-facing name (e.g., 'Color', 'Size')", max_length=100, unique=True, verbose_name='Attribute Name')),
                ('code', models.SlugField(help_text="Internal identifier (e.g., 'color', 'size')", max_length=100, unique=True, verbose_name='Attribute Code')),
                ('is_required', models.BooleanField(default=True, help_text='Must this attribute be specified for all variants?', verbose_name='Required')),
            ],
            options={
                'verbose_name': 'Product Attribute',
                'verbose_name_plural': 'Product Attributes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='products_pr_code_df414c_idx')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(blank=True, help_text='Attributes defining variants', related_name='products', to='products.productattribute', verbose_name='Variant Attributes'),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when object was soft-deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of creation', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for product category', max_length=100, unique=True, verbose_name='Category Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=True, help_text='Unique URL identifier for the category', populate_from='name', unique=True, verbose_name='Category URL Slug')),
                ('description', models.TextField(blank=True, help_text='Detailed category description for SEO and informational purposes', verbose_name='Description')),
                ('featured_image', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Representative image for the category (max 3000x3000)', null=True, upload_to=eleganza.products.validators.category_image_path, validators=[eleganza.products.validators.CategoryImageValidator()], verbose_name='Featured Image')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Toggle category visibility in storefront', verbose_name='Active')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='Parent category for hierarchical organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.productcategory', verbose_name='Parent Category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory', verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when object was soft-deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of creation', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(help_text='High-quality product image', upload_to=eleganza.products.validators.product_image_path, validators=[eleganza.products.validators.ProductImageValidator()], verbose_name='Product Image')),
                ('is_primary', models.BooleanField(default=False, help_text='Main display image', verbose_name='Primary Image')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display priority (lower first)', verbose_name='Sort Order')),
                ('caption', models.CharField(blank=True, help_text='Accessibility description', max_length=255, verbose_name='Caption')),
                ('product', models.ForeignKey(blank=True, help_text='General product images', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
                ('variant', models.ForeignKey(blank=True, help_text='Variant-specific images', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['-is_primary', 'sort_order'],
            },
        ),
        migrations.AddField(
            model_name='productvariant',
            name='options',
            field=models.ManyToManyField(help_text='Chosen attribute values', related_name='variants', to='products.productoption', verbose_name='Selected Options'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.productattribute', verbose_name='Attribute'),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, editable=False, help_text='Timestamp when object was soft-deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of creation', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='1 (Poor) to 5 (Excellent)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('title', models.CharField(help_text='Brief summary', max_length=255, verbose_name='Review Title')),
                ('comment', models.TextField(help_text='Detailed feedback', verbose_name='Review Comment')),
                ('is_approved', models.BooleanField(db_index=True, default=False, help_text='Public visibility', verbose_name='Approved')),
                ('helpful_votes', models.PositiveIntegerField(default=0, editable=False, verbose_name='Helpful Votes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
