# Generated by Django 5.0.12 on 2025-03-25 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_cartitem_product'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, limit_choices_to={'user__type': 'CUSTOMER'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.address', verbose_name='Shipping Address'),
        ),
    ]
