# Generated by Django 5.0.12 on 2025-03-23 20:14

import django.db.models.deletion
import django_countries.fields
import eleganza.users.validators
import imagekit.models.fields
import phonenumber_field.modelfields
import timezone_field.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_primary', 'city'], 'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='teammemberprofile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_email_6f2530_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_type_3fc058_idx',
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_passwords',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(db_index=True, max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(default='LY', max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Primary Address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(help_text='Building number and street name', max_length=255, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='User profile image (WEBP format)', null=True, upload_to=eleganza.users.validators.secure_avatar_name, validators=[eleganza.users.validators.WebPSecurityValidator()], verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='default_currency',
            field=models.CharField(choices=[('LYD', 'Libyan Dinar')], default='LYD', max_length=3, verbose_name='Default Currency'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='en-us', help_text='Interface language preference', max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='loyalty_points',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Loyalty Points'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='International format (+CountryCode...)', max_length=128, null=True, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='UTC', help_text="User's preferred timezone", verbose_name='Timezone'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL, verbose_name='System User'),
        ),
        migrations.AlterField(
            model_name='passwordhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='passwordhistory',
            name='password',
            field=models.CharField(help_text='Hashed password value', max_length=255, verbose_name='Password Hash'),
        ),
        migrations.AlterField(
            model_name='teammemberprofile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='User profile image (WEBP format)', null=True, upload_to=eleganza.users.validators.secure_avatar_name, validators=[eleganza.users.validators.WebPSecurityValidator()], verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='teammemberprofile',
            name='default_currency',
            field=models.CharField(choices=[('LYD', 'Libyan Dinar')], default='LYD', max_length=3, verbose_name='Default Currency'),
        ),
        migrations.AlterField(
            model_name='teammemberprofile',
            name='department',
            field=models.CharField(choices=[('sales', 'Sales'), ('support', 'Support'), ('management', 'Management')], db_index=True, max_length=50, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='teammemberprofile',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='en-us', help_text='Interface language preference', max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='teammemberprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='International format (+CountryCode...)', max_length=128, null=True, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='teammemberprofile',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='UTC', help_text="User's preferred timezone", verbose_name='Timezone'),
        ),
        migrations.AlterField(
            model_name='teammemberprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL, verbose_name='System User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, help_text='Verified contact email address', max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('TEAM_MEMBER', 'Team Member')], db_index=True, default='CUSTOMER', max_length=20, verbose_name='User Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public user identifier for API interactions', unique=True),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('user', 'street', 'city', 'postal_code'), name='unique_user_address'),
        ),
        migrations.AddConstraint(
            model_name='passwordhistory',
            constraint=models.UniqueConstraint(fields=('user', 'password'), name='unique_password_per_user'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('email',), name='unique_active_email'),
        ),
    ]
