# Generated by Django 5.0.12 on 2025-03-12 07:17

import django.core.validators
import eleganza.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address_passwordhistory_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='media/avatars/default.webp', help_text="User's profile picture or avatar. Allowed formats: JPG, JPEG, PNG, WEBP. Max size: 2MB.", null=True, upload_to=eleganza.users.validators.rename_avatar, validators=[eleganza.users.validators.validate_avatar, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
