# Generated by Django 5.0.12 on 2025-03-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_address_options_alter_customerprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, help_text='Public facing name (optional)', max_length=150, verbose_name='display name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Verified contact email address', max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
