# Generated by Django 5.0.12 on 2025-03-23 20:57

import eleganza.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_user_display_name_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_active_email',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default=None, help_text='Optional. 150 characters or fewer. Letters, digits, spaces, and @/./+/-/_ only.', max_length=150, null=True, unique=True, validators=[eleganza.users.models.SpaceAllowedUsernameValidator()], verbose_name='username'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('username__isnull', False)), fields=('username',), name='unique_non_empty_username'),
        ),
    ]
