# Generated by Django 5.0.12 on 2025-03-23 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_remove_user_unique_active_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teammemberprofile',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='passwordhistory',
            name='unique_password_per_user',
        ),
    ]
