# Generated by Django 5.0.12 on 2025-03-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Unique email address used for login and communication.', max_length=254, null=True, unique=True),
        ),
    ]
