# Generated by Django 5.0.12 on 2025-03-13 00:34

import django.core.validators
import django.db.models.deletion
import django_countries.fields
import eleganza.users.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'address', 'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='passwordhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'password history', 'verbose_name_plural': 'password histories'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(help_text='Country location.', max_length=2),
        ),
        migrations.AlterField(
            model_name='address',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft deletion timestamp.', null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Default address flag.'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(help_text='Postal or ZIP code.', max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(help_text='Associated user account.', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='address',
            name='version',
            field=models.IntegerField(default=0, help_text='Version number for changes.'),
        ),
        migrations.AlterField(
            model_name='passwordhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when password was set.'),
        ),
        migrations.AlterField(
            model_name='passwordhistory',
            name='password_hash',
            field=models.CharField(help_text='Securely hashed password representation.', max_length=255),
        ),
        migrations.AlterField(
            model_name='passwordhistory',
            name='user',
            field=models.ForeignKey(help_text='Associated user account.', on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.webp', help_text='Profile picture. Formats: JPG/PNG/WEBP. Max 2MB.', null=True, upload_to=eleganza.users.validators.rename_avatar, validators=[eleganza.users.validators.validate_avatar, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth for age verification.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp for soft deletion.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, help_text='Timestamp until which the account is locked.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False, help_text='Flag indicating if multi-factor authentication (MFA) is enabled.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='version',
            field=models.IntegerField(default=0, editable=False, help_text='Version number for concurrency control.'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='users_user_created_cf865c_idx'),
        ),
    ]
