# Generated by Django 5.0.12 on 2025-03-13 03:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_address_options_alter_passwordhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, help_text='Unique email address used for login and communication.', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
