# Generated by Django 5.0.12 on 2025-03-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MODERATOR', 'Moderator'), ('STAFF', 'Staff'), ('SELLER', 'Seller'), ('DELIVERY', 'Delivery Personnel'), ('CUSTOMER', 'Customer')], default='CUSTOMER', help_text="User's role in the system.", max_length=20),
        ),
    ]
