# Generated by Django 5.0.12 on 2025-03-15 04:48

import django.core.validators
import django.db.models.deletion
import django_countries.fields
import djmoney.models.fields
import eleganza.users.validators
import phonenumber_field.modelfields
import timezone_field.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0017_deleteduser_alter_address_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeletedUser',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'address', 'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='passwordhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'password history', 'verbose_name_plural': 'password histories'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_deleted_37c818_idx',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(help_text='City or locality name.', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(help_text='Country location.', max_length=2),
        ),
        migrations.AlterField(
            model_name='address',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft deletion timestamp.', null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Default address flag.'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(help_text='Postal or ZIP code.', max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(help_text='State, province, or region.', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(help_text='Street name and number.', max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(help_text='Associated user account.', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='address',
            name='version',
            field=models.IntegerField(default=0, help_text='Version number for changes.'),
        ),
        migrations.AlterField(
            model_name='passwordhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when password was set.'),
        ),
        migrations.AlterField(
            model_name='passwordhistory',
            name='password_hash',
            field=models.CharField(help_text='Securely hashed password representation.', max_length=255),
        ),
        migrations.AlterField(
            model_name='passwordhistory',
            name='user',
            field=models.ForeignKey(help_text='Associated user account.', on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.webp', help_text='Profile picture. Formats: JPG/PNG/WEBP. Max 2MB.', null=True, upload_to=eleganza.users.validators.rename_avatar, validators=[eleganza.users.validators.validate_avatar, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='user',
            name='data_consent',
            field=models.BooleanField(default=False, help_text='Flag indicating if the user has consented to data processing.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='data_consent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the user gave data processing consent.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth for age verification.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_currency',
            field=djmoney.models.fields.CurrencyField(default='USD', help_text="User's preferred currency for transactions and pricing.", max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp for soft deletion.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Unique email address used for login and communication.', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='failed_login_attempts',
            field=models.IntegerField(default=0, help_text='Number of consecutive failed login attempts.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False, help_text="Flag indicating if the user's phone number has been verified."),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(default='en', help_text="User's preferred language (ISO 639-1 code).", max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, help_text='Timestamp until which the account is locked.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='marketing_consent',
            field=models.BooleanField(default=False, help_text='Flag indicating if the user has consented to receive marketing communications.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='marketing_consent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the user gave marketing consent.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_updated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last password change.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="User's phone number in international format.", max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, help_text="Timestamp when the user's phone number was verified.", null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='UTC', help_text="User's preferred timezone for displaying dates and times."),
        ),
        migrations.AlterField(
            model_name='user',
            name='version',
            field=models.IntegerField(default=0, editable=False, help_text='Version number for concurrency control.'),
        ),
        migrations.AlterUniqueTogether(
            name='passwordhistory',
            unique_together={('user', 'password_hash')},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'deleted_at'], name='users_user_is_acti_d0475d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='users_user_created_cf865c_idx'),
        ),
    ]
