# Generated by Django 5.0.12 on 2025-03-15 04:58

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_default_currency_alter_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='USD', help_text="User's preferred currency for transactions and pricing.", max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Spanish'), ('fr', 'French')], default='en', help_text="User's preferred language (ISO 639-1 code).", max_length=10),
        ),
    ]
