# Generated by Django 5.0.12 on 2025-03-15 04:58

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_user_default_currency_alter_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('LYD', 'Libyan Dinar'), ('USD', 'US Dollar')], default='USD', help_text="User's preferred currency for transactions and pricing.", max_length=3),
        ),
    ]
