# Generated by Django 5.0.12 on 2025-03-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_user_default_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', help_text="User's preferred language (ISO 639-1 code).", max_length=10),
        ),
    ]
