# Generated by Django 5.0.12 on 2025-03-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Optional. Unique username for the user.', max_length=150, null=True, unique=True),
        ),
    ]
